### ISSUE TITLE
I broke it?

### ISSUE THREAD

**Issue by ghost** [ryanjgill/mkr1000#1]
The program told me to give this to you! please help!

[npm-debug.txt](https://github.com/ryanjgill/mkr1000/files/207828/npm-debug.txt)

**Comment by ghost** [comment]
Nope! i fixed that error with `npm install`, but that generated this error:

```
Unable to connect!
Please make sure you have the latest StandardFirmataWifi sketch loaded on the MKR1000
```

I have the sketch loaded onto my arduino too.
[StandardFirmataWiFiTest.zip](https://github.com/ryanjgill/mkr1000/files/207845/StandardFirmataWiFiTest.zip)

edit: when i try to ping 192.168.1.9, I get no return

**Comment by ryanjgill** [comment]
Ok it appears that the mkr1000 is having issues connecting to you home network. When you are loading the StandardFirmataWifi sketch, you can uncommit the serial debugger line. That will allow you to see the output in the serial monitor in the Arduino IDE. I have a lil demo of this process in this video [Full app install](https://youtu.be/XD4Cotwo1-4?t=10m26s) Jump forward to around 10:30.

After you comfirm the mkr1000 is connecting, make sure to comment out that line again and reload the sketch.

**Comment by ghost** [comment]
I fixed it! It turns out some networks reject 192.168.1.9 as an ip address! What you have to do is get an IP address, not static, and then assign the static IP to the IP you received without static on. DON'T FORGET TO CHANGE THE ADDRESS IN THE J5 FILE TOO!

**Comment by ryanjgill** [comment]
Nice find @CinnamonDanish, glad you were able to get it working.

**Comment by ghost** [comment]
It appears that different networks require different IP ranges, is there one ip that will work the majority of the time?

**Comment by ryanjgill** [comment]
I think it will just depend on the router and what ports are open. If you can connect without using the static ip option in the Standard Firmata Wifi sketch, then you can check the serial monitor and just set the static ip to the one it connects on. 

You will need to update the ip address in the JS just as you mentioned earlier.

**Comment by ghost** [comment]
Is there a way to write the JS so that it scans for the arduino, (i.e. without static IP), and attempts connection on that network?

**Comment by ryanjgill** [comment]
I was only able to get it to work by hardcoding the ip address and is the reason for using the static ip option in the firmata config. 

If you find a way to scan for it or make it more dynamic, please submit a pull request and I'll pull it in.
